#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopicTool
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="topic")]
	public partial class TopicDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChuyenDe(ChuyenDe instance);
    partial void UpdateChuyenDe(ChuyenDe instance);
    partial void DeleteChuyenDe(ChuyenDe instance);
    partial void InsertThueKhoan(ThueKhoan instance);
    partial void UpdateThueKhoan(ThueKhoan instance);
    partial void DeleteThueKhoan(ThueKhoan instance);
    partial void InsertCTThueKhoan(CTThueKhoan instance);
    partial void UpdateCTThueKhoan(CTThueKhoan instance);
    partial void DeleteCTThueKhoan(CTThueKhoan instance);
    partial void InsertDeTai(DeTai instance);
    partial void UpdateDeTai(DeTai instance);
    partial void DeleteDeTai(DeTai instance);
    partial void InsertThanhVien(ThanhVien instance);
    partial void UpdateThanhVien(ThanhVien instance);
    partial void DeleteThanhVien(ThanhVien instance);
    #endregion
		
		public TopicDataClassesDataContext() : 
				base(global::TopicTool.Properties.Settings.Default.topicConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TopicDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TopicDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TopicDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TopicDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChuyenDe> ChuyenDes
		{
			get
			{
				return this.GetTable<ChuyenDe>();
			}
		}
		
		public System.Data.Linq.Table<ThueKhoan> ThueKhoans
		{
			get
			{
				return this.GetTable<ThueKhoan>();
			}
		}
		
		public System.Data.Linq.Table<CTThueKhoan> CTThueKhoans
		{
			get
			{
				return this.GetTable<CTThueKhoan>();
			}
		}
		
		public System.Data.Linq.Table<DeTai> DeTais
		{
			get
			{
				return this.GetTable<DeTai>();
			}
		}
		
		public System.Data.Linq.Table<ThanhVien> ThanhViens
		{
			get
			{
				return this.GetTable<ThanhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuyenDe")]
	public partial class ChuyenDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_chuyende;
		
		private System.Nullable<int> _id_detai;
		
		private string _maso;
		
		private string _noidung;
		
		private string _noidung_tomtat;
		
		private string _sanpham;
		
		private System.Nullable<int> _sotien;
		
		private EntitySet<CTThueKhoan> _CTThueKhoans;
		
		private EntityRef<DeTai> _DeTai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_chuyendeChanging(int value);
    partial void Onid_chuyendeChanged();
    partial void Onid_detaiChanging(System.Nullable<int> value);
    partial void Onid_detaiChanged();
    partial void OnmasoChanging(string value);
    partial void OnmasoChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void Onnoidung_tomtatChanging(string value);
    partial void Onnoidung_tomtatChanged();
    partial void OnsanphamChanging(string value);
    partial void OnsanphamChanged();
    partial void OnsotienChanging(System.Nullable<int> value);
    partial void OnsotienChanged();
    #endregion
		
		public ChuyenDe()
		{
			this._CTThueKhoans = new EntitySet<CTThueKhoan>(new Action<CTThueKhoan>(this.attach_CTThueKhoans), new Action<CTThueKhoan>(this.detach_CTThueKhoans));
			this._DeTai = default(EntityRef<DeTai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_chuyende", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_chuyende
		{
			get
			{
				return this._id_chuyende;
			}
			set
			{
				if ((this._id_chuyende != value))
				{
					this.Onid_chuyendeChanging(value);
					this.SendPropertyChanging();
					this._id_chuyende = value;
					this.SendPropertyChanged("id_chuyende");
					this.Onid_chuyendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detai", DbType="Int")]
		public System.Nullable<int> id_detai
		{
			get
			{
				return this._id_detai;
			}
			set
			{
				if ((this._id_detai != value))
				{
					if (this._DeTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_detaiChanging(value);
					this.SendPropertyChanging();
					this._id_detai = value;
					this.SendPropertyChanged("id_detai");
					this.Onid_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maso", DbType="VarChar(20)")]
		public string maso
		{
			get
			{
				return this._maso;
			}
			set
			{
				if ((this._maso != value))
				{
					this.OnmasoChanging(value);
					this.SendPropertyChanging();
					this._maso = value;
					this.SendPropertyChanged("maso");
					this.OnmasoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(500)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung_tomtat", DbType="NVarChar(200)")]
		public string noidung_tomtat
		{
			get
			{
				return this._noidung_tomtat;
			}
			set
			{
				if ((this._noidung_tomtat != value))
				{
					this.Onnoidung_tomtatChanging(value);
					this.SendPropertyChanging();
					this._noidung_tomtat = value;
					this.SendPropertyChanged("noidung_tomtat");
					this.Onnoidung_tomtatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham", DbType="NVarChar(200)")]
		public string sanpham
		{
			get
			{
				return this._sanpham;
			}
			set
			{
				if ((this._sanpham != value))
				{
					this.OnsanphamChanging(value);
					this.SendPropertyChanging();
					this._sanpham = value;
					this.SendPropertyChanged("sanpham");
					this.OnsanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotien", DbType="Int")]
		public System.Nullable<int> sotien
		{
			get
			{
				return this._sotien;
			}
			set
			{
				if ((this._sotien != value))
				{
					this.OnsotienChanging(value);
					this.SendPropertyChanging();
					this._sotien = value;
					this.SendPropertyChanged("sotien");
					this.OnsotienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenDe_CTThueKhoan", Storage="_CTThueKhoans", ThisKey="id_chuyende", OtherKey="id_chuyende")]
		public EntitySet<CTThueKhoan> CTThueKhoans
		{
			get
			{
				return this._CTThueKhoans;
			}
			set
			{
				this._CTThueKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTai_ChuyenDe", Storage="_DeTai", ThisKey="id_detai", OtherKey="id_detai", IsForeignKey=true)]
		public DeTai DeTai
		{
			get
			{
				return this._DeTai.Entity;
			}
			set
			{
				DeTai previousValue = this._DeTai.Entity;
				if (((previousValue != value) 
							|| (this._DeTai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeTai.Entity = null;
						previousValue.ChuyenDes.Remove(this);
					}
					this._DeTai.Entity = value;
					if ((value != null))
					{
						value.ChuyenDes.Add(this);
						this._id_detai = value.id_detai;
					}
					else
					{
						this._id_detai = default(Nullable<int>);
					}
					this.SendPropertyChanged("DeTai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTThueKhoans(CTThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenDe = this;
		}
		
		private void detach_CTThueKhoans(CTThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThueKhoan")]
	public partial class ThueKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_thuekhoan;
		
		private System.Nullable<int> _id_detai;
		
		private System.Nullable<int> _id_thanhvien;
		
		private string _sohd_thuekhoan;
		
		private System.Nullable<System.DateTime> _ngayky_thuekhoan;
		
		private System.Nullable<System.DateTime> _ngayketthuc_thuekhoan;
		
		private System.Nullable<System.DateTime> _ngaynghiemthu_thuekhoan;
		
		private System.Nullable<System.DateTime> _ngaythanhly_thuekhoan;
		
		private System.Nullable<System.DateTime> _ngaybiennhan_thuekhoan;
		
		private System.Nullable<int> _id_cndt;
		
		private EntitySet<CTThueKhoan> _CTThueKhoans;
		
		private EntityRef<DeTai> _DeTai;
		
		private EntityRef<ThanhVien> _ThanhVien;
		
		private EntityRef<ThanhVien> _ThanhVien1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_thuekhoanChanging(int value);
    partial void Onid_thuekhoanChanged();
    partial void Onid_detaiChanging(System.Nullable<int> value);
    partial void Onid_detaiChanged();
    partial void Onid_thanhvienChanging(System.Nullable<int> value);
    partial void Onid_thanhvienChanged();
    partial void Onsohd_thuekhoanChanging(string value);
    partial void Onsohd_thuekhoanChanged();
    partial void Onngayky_thuekhoanChanging(System.Nullable<System.DateTime> value);
    partial void Onngayky_thuekhoanChanged();
    partial void Onngayketthuc_thuekhoanChanging(System.Nullable<System.DateTime> value);
    partial void Onngayketthuc_thuekhoanChanged();
    partial void Onngaynghiemthu_thuekhoanChanging(System.Nullable<System.DateTime> value);
    partial void Onngaynghiemthu_thuekhoanChanged();
    partial void Onngaythanhly_thuekhoanChanging(System.Nullable<System.DateTime> value);
    partial void Onngaythanhly_thuekhoanChanged();
    partial void Onngaybiennhan_thuekhoanChanging(System.Nullable<System.DateTime> value);
    partial void Onngaybiennhan_thuekhoanChanged();
    partial void Onid_cndtChanging(System.Nullable<int> value);
    partial void Onid_cndtChanged();
    #endregion
		
		public ThueKhoan()
		{
			this._CTThueKhoans = new EntitySet<CTThueKhoan>(new Action<CTThueKhoan>(this.attach_CTThueKhoans), new Action<CTThueKhoan>(this.detach_CTThueKhoans));
			this._DeTai = default(EntityRef<DeTai>);
			this._ThanhVien = default(EntityRef<ThanhVien>);
			this._ThanhVien1 = default(EntityRef<ThanhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thuekhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_thuekhoan
		{
			get
			{
				return this._id_thuekhoan;
			}
			set
			{
				if ((this._id_thuekhoan != value))
				{
					this.Onid_thuekhoanChanging(value);
					this.SendPropertyChanging();
					this._id_thuekhoan = value;
					this.SendPropertyChanged("id_thuekhoan");
					this.Onid_thuekhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detai", DbType="Int")]
		public System.Nullable<int> id_detai
		{
			get
			{
				return this._id_detai;
			}
			set
			{
				if ((this._id_detai != value))
				{
					if (this._DeTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_detaiChanging(value);
					this.SendPropertyChanging();
					this._id_detai = value;
					this.SendPropertyChanged("id_detai");
					this.Onid_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thanhvien", DbType="Int")]
		public System.Nullable<int> id_thanhvien
		{
			get
			{
				return this._id_thanhvien;
			}
			set
			{
				if ((this._id_thanhvien != value))
				{
					if (this._ThanhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_thanhvienChanging(value);
					this.SendPropertyChanging();
					this._id_thanhvien = value;
					this.SendPropertyChanged("id_thanhvien");
					this.Onid_thanhvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sohd_thuekhoan", DbType="NVarChar(50)")]
		public string sohd_thuekhoan
		{
			get
			{
				return this._sohd_thuekhoan;
			}
			set
			{
				if ((this._sohd_thuekhoan != value))
				{
					this.Onsohd_thuekhoanChanging(value);
					this.SendPropertyChanging();
					this._sohd_thuekhoan = value;
					this.SendPropertyChanged("sohd_thuekhoan");
					this.Onsohd_thuekhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayky_thuekhoan", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngayky_thuekhoan
		{
			get
			{
				return this._ngayky_thuekhoan;
			}
			set
			{
				if ((this._ngayky_thuekhoan != value))
				{
					this.Onngayky_thuekhoanChanging(value);
					this.SendPropertyChanging();
					this._ngayky_thuekhoan = value;
					this.SendPropertyChanged("ngayky_thuekhoan");
					this.Onngayky_thuekhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayketthuc_thuekhoan", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngayketthuc_thuekhoan
		{
			get
			{
				return this._ngayketthuc_thuekhoan;
			}
			set
			{
				if ((this._ngayketthuc_thuekhoan != value))
				{
					this.Onngayketthuc_thuekhoanChanging(value);
					this.SendPropertyChanging();
					this._ngayketthuc_thuekhoan = value;
					this.SendPropertyChanged("ngayketthuc_thuekhoan");
					this.Onngayketthuc_thuekhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynghiemthu_thuekhoan", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngaynghiemthu_thuekhoan
		{
			get
			{
				return this._ngaynghiemthu_thuekhoan;
			}
			set
			{
				if ((this._ngaynghiemthu_thuekhoan != value))
				{
					this.Onngaynghiemthu_thuekhoanChanging(value);
					this.SendPropertyChanging();
					this._ngaynghiemthu_thuekhoan = value;
					this.SendPropertyChanged("ngaynghiemthu_thuekhoan");
					this.Onngaynghiemthu_thuekhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythanhly_thuekhoan", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngaythanhly_thuekhoan
		{
			get
			{
				return this._ngaythanhly_thuekhoan;
			}
			set
			{
				if ((this._ngaythanhly_thuekhoan != value))
				{
					this.Onngaythanhly_thuekhoanChanging(value);
					this.SendPropertyChanging();
					this._ngaythanhly_thuekhoan = value;
					this.SendPropertyChanged("ngaythanhly_thuekhoan");
					this.Onngaythanhly_thuekhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybiennhan_thuekhoan", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngaybiennhan_thuekhoan
		{
			get
			{
				return this._ngaybiennhan_thuekhoan;
			}
			set
			{
				if ((this._ngaybiennhan_thuekhoan != value))
				{
					this.Onngaybiennhan_thuekhoanChanging(value);
					this.SendPropertyChanging();
					this._ngaybiennhan_thuekhoan = value;
					this.SendPropertyChanged("ngaybiennhan_thuekhoan");
					this.Onngaybiennhan_thuekhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cndt", DbType="Int")]
		public System.Nullable<int> id_cndt
		{
			get
			{
				return this._id_cndt;
			}
			set
			{
				if ((this._id_cndt != value))
				{
					if (this._ThanhVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_cndtChanging(value);
					this.SendPropertyChanging();
					this._id_cndt = value;
					this.SendPropertyChanged("id_cndt");
					this.Onid_cndtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThueKhoan_CTThueKhoan", Storage="_CTThueKhoans", ThisKey="id_thuekhoan", OtherKey="id_thuekhoan")]
		public EntitySet<CTThueKhoan> CTThueKhoans
		{
			get
			{
				return this._CTThueKhoans;
			}
			set
			{
				this._CTThueKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTai_ThueKhoan", Storage="_DeTai", ThisKey="id_detai", OtherKey="id_detai", IsForeignKey=true)]
		public DeTai DeTai
		{
			get
			{
				return this._DeTai.Entity;
			}
			set
			{
				DeTai previousValue = this._DeTai.Entity;
				if (((previousValue != value) 
							|| (this._DeTai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeTai.Entity = null;
						previousValue.ThueKhoans.Remove(this);
					}
					this._DeTai.Entity = value;
					if ((value != null))
					{
						value.ThueKhoans.Add(this);
						this._id_detai = value.id_detai;
					}
					else
					{
						this._id_detai = default(Nullable<int>);
					}
					this.SendPropertyChanged("DeTai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_ThueKhoan", Storage="_ThanhVien", ThisKey="id_thanhvien", OtherKey="id_thanhvien", IsForeignKey=true)]
		public ThanhVien ThanhVien
		{
			get
			{
				return this._ThanhVien.Entity;
			}
			set
			{
				ThanhVien previousValue = this._ThanhVien.Entity;
				if (((previousValue != value) 
							|| (this._ThanhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhVien.Entity = null;
						previousValue.ThueKhoans.Remove(this);
					}
					this._ThanhVien.Entity = value;
					if ((value != null))
					{
						value.ThueKhoans.Add(this);
						this._id_thanhvien = value.id_thanhvien;
					}
					else
					{
						this._id_thanhvien = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThanhVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_ThueKhoan1", Storage="_ThanhVien1", ThisKey="id_cndt", OtherKey="id_thanhvien", IsForeignKey=true)]
		public ThanhVien ThanhVien1
		{
			get
			{
				return this._ThanhVien1.Entity;
			}
			set
			{
				ThanhVien previousValue = this._ThanhVien1.Entity;
				if (((previousValue != value) 
							|| (this._ThanhVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhVien1.Entity = null;
						previousValue.ThueKhoans1.Remove(this);
					}
					this._ThanhVien1.Entity = value;
					if ((value != null))
					{
						value.ThueKhoans1.Add(this);
						this._id_cndt = value.id_thanhvien;
					}
					else
					{
						this._id_cndt = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThanhVien1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTThueKhoans(CTThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ThueKhoan = this;
		}
		
		private void detach_CTThueKhoans(CTThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ThueKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTThueKhoan")]
	public partial class CTThueKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_thuekhoan;
		
		private int _id_chuyende;
		
		private EntityRef<ChuyenDe> _ChuyenDe;
		
		private EntityRef<ThueKhoan> _ThueKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_thuekhoanChanging(int value);
    partial void Onid_thuekhoanChanged();
    partial void Onid_chuyendeChanging(int value);
    partial void Onid_chuyendeChanged();
    #endregion
		
		public CTThueKhoan()
		{
			this._ChuyenDe = default(EntityRef<ChuyenDe>);
			this._ThueKhoan = default(EntityRef<ThueKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thuekhoan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_thuekhoan
		{
			get
			{
				return this._id_thuekhoan;
			}
			set
			{
				if ((this._id_thuekhoan != value))
				{
					if (this._ThueKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_thuekhoanChanging(value);
					this.SendPropertyChanging();
					this._id_thuekhoan = value;
					this.SendPropertyChanged("id_thuekhoan");
					this.Onid_thuekhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_chuyende", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_chuyende
		{
			get
			{
				return this._id_chuyende;
			}
			set
			{
				if ((this._id_chuyende != value))
				{
					if (this._ChuyenDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_chuyendeChanging(value);
					this.SendPropertyChanging();
					this._id_chuyende = value;
					this.SendPropertyChanged("id_chuyende");
					this.Onid_chuyendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenDe_CTThueKhoan", Storage="_ChuyenDe", ThisKey="id_chuyende", OtherKey="id_chuyende", IsForeignKey=true)]
		public ChuyenDe ChuyenDe
		{
			get
			{
				return this._ChuyenDe.Entity;
			}
			set
			{
				ChuyenDe previousValue = this._ChuyenDe.Entity;
				if (((previousValue != value) 
							|| (this._ChuyenDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuyenDe.Entity = null;
						previousValue.CTThueKhoans.Remove(this);
					}
					this._ChuyenDe.Entity = value;
					if ((value != null))
					{
						value.CTThueKhoans.Add(this);
						this._id_chuyende = value.id_chuyende;
					}
					else
					{
						this._id_chuyende = default(int);
					}
					this.SendPropertyChanged("ChuyenDe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThueKhoan_CTThueKhoan", Storage="_ThueKhoan", ThisKey="id_thuekhoan", OtherKey="id_thuekhoan", IsForeignKey=true)]
		public ThueKhoan ThueKhoan
		{
			get
			{
				return this._ThueKhoan.Entity;
			}
			set
			{
				ThueKhoan previousValue = this._ThueKhoan.Entity;
				if (((previousValue != value) 
							|| (this._ThueKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThueKhoan.Entity = null;
						previousValue.CTThueKhoans.Remove(this);
					}
					this._ThueKhoan.Entity = value;
					if ((value != null))
					{
						value.CTThueKhoans.Add(this);
						this._id_thuekhoan = value.id_thuekhoan;
					}
					else
					{
						this._id_thuekhoan = default(int);
					}
					this.SendPropertyChanged("ThueKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeTai")]
	public partial class DeTai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_detai;
		
		private string _ten_detai;
		
		private string _sohd_detai;
		
		private System.Nullable<System.DateTime> _ngayky_detai;
		
		private System.Nullable<int> _id_tochuc;
		
		private System.Nullable<int> _id_cndt1;
		
		private System.Nullable<int> _id_cndt2;
		
		private EntitySet<ChuyenDe> _ChuyenDes;
		
		private EntitySet<ThueKhoan> _ThueKhoans;
		
		private EntityRef<ThanhVien> _ThanhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detaiChanging(int value);
    partial void Onid_detaiChanged();
    partial void Onten_detaiChanging(string value);
    partial void Onten_detaiChanged();
    partial void Onsohd_detaiChanging(string value);
    partial void Onsohd_detaiChanged();
    partial void Onngayky_detaiChanging(System.Nullable<System.DateTime> value);
    partial void Onngayky_detaiChanged();
    partial void Onid_tochucChanging(System.Nullable<int> value);
    partial void Onid_tochucChanged();
    partial void Onid_cndt1Changing(System.Nullable<int> value);
    partial void Onid_cndt1Changed();
    partial void Onid_cndt2Changing(System.Nullable<int> value);
    partial void Onid_cndt2Changed();
    #endregion
		
		public DeTai()
		{
			this._ChuyenDes = new EntitySet<ChuyenDe>(new Action<ChuyenDe>(this.attach_ChuyenDes), new Action<ChuyenDe>(this.detach_ChuyenDes));
			this._ThueKhoans = new EntitySet<ThueKhoan>(new Action<ThueKhoan>(this.attach_ThueKhoans), new Action<ThueKhoan>(this.detach_ThueKhoans));
			this._ThanhVien = default(EntityRef<ThanhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_detai
		{
			get
			{
				return this._id_detai;
			}
			set
			{
				if ((this._id_detai != value))
				{
					this.Onid_detaiChanging(value);
					this.SendPropertyChanging();
					this._id_detai = value;
					this.SendPropertyChanged("id_detai");
					this.Onid_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_detai", DbType="NVarChar(200)")]
		public string ten_detai
		{
			get
			{
				return this._ten_detai;
			}
			set
			{
				if ((this._ten_detai != value))
				{
					this.Onten_detaiChanging(value);
					this.SendPropertyChanging();
					this._ten_detai = value;
					this.SendPropertyChanged("ten_detai");
					this.Onten_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sohd_detai", DbType="NVarChar(50)")]
		public string sohd_detai
		{
			get
			{
				return this._sohd_detai;
			}
			set
			{
				if ((this._sohd_detai != value))
				{
					this.Onsohd_detaiChanging(value);
					this.SendPropertyChanging();
					this._sohd_detai = value;
					this.SendPropertyChanged("sohd_detai");
					this.Onsohd_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayky_detai", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngayky_detai
		{
			get
			{
				return this._ngayky_detai;
			}
			set
			{
				if ((this._ngayky_detai != value))
				{
					this.Onngayky_detaiChanging(value);
					this.SendPropertyChanging();
					this._ngayky_detai = value;
					this.SendPropertyChanged("ngayky_detai");
					this.Onngayky_detaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tochuc", DbType="Int")]
		public System.Nullable<int> id_tochuc
		{
			get
			{
				return this._id_tochuc;
			}
			set
			{
				if ((this._id_tochuc != value))
				{
					if (this._ThanhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tochucChanging(value);
					this.SendPropertyChanging();
					this._id_tochuc = value;
					this.SendPropertyChanged("id_tochuc");
					this.Onid_tochucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cndt1", DbType="Int")]
		public System.Nullable<int> id_cndt1
		{
			get
			{
				return this._id_cndt1;
			}
			set
			{
				if ((this._id_cndt1 != value))
				{
					this.Onid_cndt1Changing(value);
					this.SendPropertyChanging();
					this._id_cndt1 = value;
					this.SendPropertyChanged("id_cndt1");
					this.Onid_cndt1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cndt2", DbType="Int")]
		public System.Nullable<int> id_cndt2
		{
			get
			{
				return this._id_cndt2;
			}
			set
			{
				if ((this._id_cndt2 != value))
				{
					this.Onid_cndt2Changing(value);
					this.SendPropertyChanging();
					this._id_cndt2 = value;
					this.SendPropertyChanged("id_cndt2");
					this.Onid_cndt2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTai_ChuyenDe", Storage="_ChuyenDes", ThisKey="id_detai", OtherKey="id_detai")]
		public EntitySet<ChuyenDe> ChuyenDes
		{
			get
			{
				return this._ChuyenDes;
			}
			set
			{
				this._ChuyenDes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTai_ThueKhoan", Storage="_ThueKhoans", ThisKey="id_detai", OtherKey="id_detai")]
		public EntitySet<ThueKhoan> ThueKhoans
		{
			get
			{
				return this._ThueKhoans;
			}
			set
			{
				this._ThueKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_DeTai", Storage="_ThanhVien", ThisKey="id_tochuc", OtherKey="id_thanhvien", IsForeignKey=true)]
		public ThanhVien ThanhVien
		{
			get
			{
				return this._ThanhVien.Entity;
			}
			set
			{
				ThanhVien previousValue = this._ThanhVien.Entity;
				if (((previousValue != value) 
							|| (this._ThanhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhVien.Entity = null;
						previousValue.DeTais.Remove(this);
					}
					this._ThanhVien.Entity = value;
					if ((value != null))
					{
						value.DeTais.Add(this);
						this._id_tochuc = value.id_thanhvien;
					}
					else
					{
						this._id_tochuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThanhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChuyenDes(ChuyenDe entity)
		{
			this.SendPropertyChanging();
			entity.DeTai = this;
		}
		
		private void detach_ChuyenDes(ChuyenDe entity)
		{
			this.SendPropertyChanging();
			entity.DeTai = null;
		}
		
		private void attach_ThueKhoans(ThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.DeTai = this;
		}
		
		private void detach_ThueKhoans(ThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.DeTai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhVien")]
	public partial class ThanhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_thanhvien;
		
		private string _hoten;
		
		private string _gioitinh;
		
		private string _chucvu;
		
		private string _hocvi;
		
		private string _quanham;
		
		private string _cmnd;
		
		private string _ngaycmnd;
		
		private string _noicap;
		
		private string _diachi;
		
		private string _dienthoai;
		
		private string _sotk;
		
		private string _nganhang;
		
		private EntitySet<ThueKhoan> _ThueKhoans;
		
		private EntitySet<ThueKhoan> _ThueKhoans1;
		
		private EntitySet<DeTai> _DeTais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_thanhvienChanging(int value);
    partial void Onid_thanhvienChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnchucvuChanging(string value);
    partial void OnchucvuChanged();
    partial void OnhocviChanging(string value);
    partial void OnhocviChanged();
    partial void OnquanhamChanging(string value);
    partial void OnquanhamChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnngaycmndChanging(string value);
    partial void OnngaycmndChanged();
    partial void OnnoicapChanging(string value);
    partial void OnnoicapChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OnsotkChanging(string value);
    partial void OnsotkChanged();
    partial void OnnganhangChanging(string value);
    partial void OnnganhangChanged();
    #endregion
		
		public ThanhVien()
		{
			this._ThueKhoans = new EntitySet<ThueKhoan>(new Action<ThueKhoan>(this.attach_ThueKhoans), new Action<ThueKhoan>(this.detach_ThueKhoans));
			this._ThueKhoans1 = new EntitySet<ThueKhoan>(new Action<ThueKhoan>(this.attach_ThueKhoans1), new Action<ThueKhoan>(this.detach_ThueKhoans1));
			this._DeTais = new EntitySet<DeTai>(new Action<DeTai>(this.attach_DeTais), new Action<DeTai>(this.detach_DeTais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thanhvien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_thanhvien
		{
			get
			{
				return this._id_thanhvien;
			}
			set
			{
				if ((this._id_thanhvien != value))
				{
					this.Onid_thanhvienChanging(value);
					this.SendPropertyChanging();
					this._id_thanhvien = value;
					this.SendPropertyChanged("id_thanhvien");
					this.Onid_thanhvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucvu", DbType="NVarChar(50)")]
		public string chucvu
		{
			get
			{
				return this._chucvu;
			}
			set
			{
				if ((this._chucvu != value))
				{
					this.OnchucvuChanging(value);
					this.SendPropertyChanging();
					this._chucvu = value;
					this.SendPropertyChanged("chucvu");
					this.OnchucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hocvi", DbType="NVarChar(10)")]
		public string hocvi
		{
			get
			{
				return this._hocvi;
			}
			set
			{
				if ((this._hocvi != value))
				{
					this.OnhocviChanging(value);
					this.SendPropertyChanging();
					this._hocvi = value;
					this.SendPropertyChanged("hocvi");
					this.OnhocviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quanham", DbType="NVarChar(50)")]
		public string quanham
		{
			get
			{
				return this._quanham;
			}
			set
			{
				if ((this._quanham != value))
				{
					this.OnquanhamChanging(value);
					this.SendPropertyChanging();
					this._quanham = value;
					this.SendPropertyChanged("quanham");
					this.OnquanhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="NVarChar(50)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycmnd", DbType="NVarChar(50)")]
		public string ngaycmnd
		{
			get
			{
				return this._ngaycmnd;
			}
			set
			{
				if ((this._ngaycmnd != value))
				{
					this.OnngaycmndChanging(value);
					this.SendPropertyChanging();
					this._ngaycmnd = value;
					this.SendPropertyChanged("ngaycmnd");
					this.OnngaycmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noicap", DbType="NVarChar(50)")]
		public string noicap
		{
			get
			{
				return this._noicap;
			}
			set
			{
				if ((this._noicap != value))
				{
					this.OnnoicapChanging(value);
					this.SendPropertyChanging();
					this._noicap = value;
					this.SendPropertyChanged("noicap");
					this.OnnoicapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(200)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="NVarChar(50)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotk", DbType="NVarChar(50)")]
		public string sotk
		{
			get
			{
				return this._sotk;
			}
			set
			{
				if ((this._sotk != value))
				{
					this.OnsotkChanging(value);
					this.SendPropertyChanging();
					this._sotk = value;
					this.SendPropertyChanged("sotk");
					this.OnsotkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nganhang", DbType="NVarChar(200)")]
		public string nganhang
		{
			get
			{
				return this._nganhang;
			}
			set
			{
				if ((this._nganhang != value))
				{
					this.OnnganhangChanging(value);
					this.SendPropertyChanging();
					this._nganhang = value;
					this.SendPropertyChanged("nganhang");
					this.OnnganhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_ThueKhoan", Storage="_ThueKhoans", ThisKey="id_thanhvien", OtherKey="id_thanhvien")]
		public EntitySet<ThueKhoan> ThueKhoans
		{
			get
			{
				return this._ThueKhoans;
			}
			set
			{
				this._ThueKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_ThueKhoan1", Storage="_ThueKhoans1", ThisKey="id_thanhvien", OtherKey="id_cndt")]
		public EntitySet<ThueKhoan> ThueKhoans1
		{
			get
			{
				return this._ThueKhoans1;
			}
			set
			{
				this._ThueKhoans1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhVien_DeTai", Storage="_DeTais", ThisKey="id_thanhvien", OtherKey="id_tochuc")]
		public EntitySet<DeTai> DeTais
		{
			get
			{
				return this._DeTais;
			}
			set
			{
				this._DeTais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThueKhoans(ThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = this;
		}
		
		private void detach_ThueKhoans(ThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = null;
		}
		
		private void attach_ThueKhoans1(ThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien1 = this;
		}
		
		private void detach_ThueKhoans1(ThueKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien1 = null;
		}
		
		private void attach_DeTais(DeTai entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = this;
		}
		
		private void detach_DeTais(DeTai entity)
		{
			this.SendPropertyChanging();
			entity.ThanhVien = null;
		}
	}
}
#pragma warning restore 1591
